import type { Metadata } from 'next';
import { Cormorant_Garamond, Jost } from 'next/font/google';
import { LANGUAGES } from '@/lib/constans';
import { ReactNode } from 'react';
import { PageParams } from '@/types';
import '@/app/globals.css';
import Footer from '@/components/layout/Footer';
import Navbar from '@/components/layout/Navbar';

const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['300', '400'],
  style: ['normal', 'italic'],
  variable: '--font-cormorant',
});

const jost = Jost({
  subsets: ['latin'],
  weight: ['300', '400'],
  variable: '--font-jost',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return LANGUAGES.map(({ id }) => ({ lang: id }));
}

type StaticProps = PageParams & { children: ReactNode };

export default async function RootLayout({ children, params }: StaticProps) {
  const { lang } = await params;
  return (
    <html
      lang={lang}
      className={`${cormorant.variable} ${jost.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-sand font-sans">
        <Navbar />
        <main className="flex flex-1 flex-col">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
